name: Bug report
about: Report a bug you have found
title: '[Bug]: '
labels: 'bug'
assignees:
 - sdk2k01
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false  
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you are experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment(desktop)
      description: |
        examples:
          - **OS**: iOS
          - **Browser**: chrome
          - **Version**: 22
      value: |
          - OS:
          - Browser:
          - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment(Smartphone)
      description: |
        examples:
          - **Device**: iPhone6
          - **OS**: iOS8.1
          - **Browser**: safari
          - **Version**: 22
      value: |
          - OS:
          - Browser:
          - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

